### PR TITLE
Unit change

### PR DESCRIPTION
**Pull request by jean-bougeois-cruz**
Added a starting imperial unit implementation. Added an activity that allows you to choose between metric and imperial on registration, and changed InputHeight and InputWeight to allow for this change. UI definitely isn't the cleanest, InputHeight needs work as right now it asks for inches rather than feet and inches if someone chooses imperial. 

Height and weight are still stored in metric, just converted back to imperial when displayed.

### CODE REVIEW

**Comment by ravern** [comment]
Cool! Just curious to know, how did you come across this project?

**Comment by jean-bougeois-cruz** [comment]
> Cool! Just curious to know, how did you come across this project?

Hey! I was browsing calorie trackers on Github and came across your app. The UI looked really clean so I thought I'd check it out. I checked your scrum board and thought the Unit Change'd be something I'd be capable of doing.

**Comment by jean-bougeois-cruz** [comment]
Fixed conflicts

**Comment by ktzy0305** [comment]
Thank you for contributing to the development of Gastronome! :+1:

**Review by ktzy0305 — APPROVED** [review]

**Pull request merged**
